id = "quazi"
name = "Quazi"
version = "0.1.0"
schema_version = 1
authors = ["quazilang"]
description = "Quazi language support"
repository = "https://github.com/quazilang/zed-quazi"

[grammars.quazi]
repository = "https://github.com/quazilang/tree-sitter"
rev = "685ebbf2760a443262a7c8deb51b04f25d2e78c9"

[language_servers.quazi]
name = "Quazi Language Server"
languages = ["Quazi"]
