id = "quazi"
name = "Quazi"
version = "0.1.0"
schema_version = 1
authors = ["quazilang"]
description = "Quazi language support"
repository = "https://github.com/quazilang/zed-quazi"

[grammars.quazi]
repository = "https://github.com/quazilang/tree-sitter"
rev = "c3d5c29393c9bcfce498f3c2f7b3a6f2c8026896"

[language_servers.quazi]
name = "Quazi Language Server"
languages = ["Quazi"]
